export const localRestaurants = [
  {
    name: "Sunny's Cafe",
    image_url: "https://via.placeholder.com/150",
    categories: ["Cafe", "Breakfast"],
    price: "$",
    reviews: 124,
    rating: 4.5,
  },
  {
    name: "Pasta Paradise",
    image_url: "https://via.placeholder.com/150",
    categories: ["Italian", "Pasta"],
    price: "$$",
    reviews: 200,
    rating: 4.7,
  },
  {
    name: "The Burger Joint",
    image_url: "https://via.placeholder.com/150",
    categories: ["Burgers", "Fast Food"],
    price: "$",
    reviews: 300,
    rating: 4.2,
  },
  {
    name: "Ocean Delights",
    image_url: "https://via.placeholder.com/150",
    categories: ["Seafood", "Fine Dining"],
    price: "$$$",
    reviews: 150,
    rating: 4.8,
  },
  {
    name: "Green Bistro",
    image_url: "https://via.placeholder.com/150",
    categories: ["Vegan", "Healthy"],
    price: "$$",
    reviews: 180,
    rating: 4.4,
  },
  {
    name: "Spice Symphony",
    image_url: "https://via.placeholder.com/150",
    categories: ["Indian", "Spicy"],
    price: "$$",
    reviews: 250,
    rating: 4.6,
  },
];
